#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

case "$DPKG_ARCH" in
powerpc|ppc64)
	# For PS3's we know these devices will exist, and we'll need them
	if grep -q PS3 /proc/cpuinfo; then
		modprobe -q ps3_storage
		modprobe -q gelic_net
		modprobe -q ohci-hcd
		modprobe -q ehci-hcd
	fi
	;;
esac
