#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if grep -q -w all_generic_ide /proc/cmdline; then
	modprobe -Qb ata_generic all_generic_ide=1
fi
