#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. ./scripts/functions

if [ -z "${resume}" ]; then
	exit 0
fi

SWAPTYPE=$(wait-for-root "${resume}")

case "${SWAPTYPE}" in
    s1suspend|s2suspend|ulsuspend|tuxonice)
	# hardcode path, uswsusp ships an resume binary too
	if [ -n "${resume_offset}" ]; then
		/bin/resume ${resume} ${resume_offset} >/dev/null 2>&1
	else
		/bin/resume ${resume} >/dev/null 2>&1
	fi
	;;
esac
