#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if [ -z "${resume}" ]; then
	exit 0
fi

case $resume in
	LABEL=*)
	resume="/dev/disk/by-label/${resume#LABEL=}"
	;;
	UUID=*)
	resume="/dev/disk/by-uuid/${resume#UUID=}"
	;;
esac

. ./scripts/functions

if [ ! -e "${resume}" ] || ! /lib/udev/vol_id "${resume}" >/dev/null 2>&1; then
	log_begin_msg "Waiting for resume device..."

	# Default delay is 5s
	if [ -z "${RESUMEDELAY}" ]; then
		slumber=5
	else
		slumber=${RESUMEDELAY}
	fi
	if [ -x /sbin/usplash_write ]; then
		/sbin/usplash_write "TIMEOUT ${slumber}" || true
	fi

	slumber=$(( ${slumber} * 10 ))
	while [ ! -e "${resume}" ] || ! /lib/udev/vol_id "${resume}" >/dev/null 2>&1; do
		/bin/sleep 0.1
		slumber=$(( ${slumber} - 1 ))
		[ ${slumber} -gt 0 ] || break
	done

	if [ ${slumber} -gt 0 ]; then
		log_end_msg 0
	else
		log_end_msg 1 || true
		exit
	fi
fi

# hardcode path, uswsusp ships an resume binary too
if [ -n "${resume_offset}" ]; then
	/bin/resume ${resume} ${resume_offset}
else
	/bin/resume ${resume}
fi
