#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if [ -z "${resume}" ] || [ ! -e /sys/power/resume ]; then
	exit 0
fi

. /scripts/functions
. /scripts/local

SWAPTYPE=$(wait-for-root "${resume}" ${RESUMEDELAY:-5})

case "${SWAPTYPE}" in
    swsuspend|s1suspend|s2suspend|ulsuspend|tuxonice)
	if [ -x /bin/plymouth ] && plymouth --ping; then
		plymouth message --text="Resuming from $resume"
	fi

	# hardcode path, uswsusp ships an resume binary too
	if [ -n "${resume_offset}" ]; then
		/bin/resume ${DEV} ${resume_offset}
	else
		/bin/resume ${DEV}
	fi
	;;
esac
