#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if [ "x${resume}" = "x" ]; then
	exit
fi

if [ ! -e "${resume}" ]; then
	exit
fi

. /scripts/functions

if [ -e /sys/power/resume ]; then
    log_begin_msg "Resuming from hibernation..."
	major=$((0x$(stat -c%t ${resume})))
	minor=$((0x$(stat -c%T ${resume})))
	echo ${major}:${minor} >/sys/power/resume
	# XXX should only return on failure, but log_end_msg doesn't understand
	# failure -mdz
    # log_end_msg 1
fi
